//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TasksWebAPI.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class T_Tasks
    {
        public int TaskID { get; set; }
        public string TaskName { get; set; }
        public string TaskType { get; set; }
        public System.DateTime DueDate { get; set; }
        public Nullable<int> QuoteNumber { get; set; }
        public string QuoteType { get; set; }
        public string Contact { get; set; }

    }
}
